FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.26.6@sha256:640a234f4bea3e399c056b7b8f9c667c4939befae8db2f14e9785e16eccd4205 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-gitea-release"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-gitea-release"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-gitea-release"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-gitea-release"

RUN apk upgrade --no-cache zlib libcrypto3 && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY --from=build /src/dist/wp-gitea-release /bin/wp-gitea-release
ENTRYPOINT ["/bin/wp-gitea-release"]
