FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.26.2@sha256:5f3787b7f902c07c7ec4f3aa91a301a3eda8133aa32661a3b3a3a86ab3a68a36 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-gitea-release"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-gitea-release"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-gitea-release"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-gitea-release"

RUN apk upgrade --no-cache zlib && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY --from=build /src/dist/wp-gitea-release /bin/wp-gitea-release
ENTRYPOINT ["/bin/wp-gitea-release"]
