FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.22@sha256:2bd56f00ff47baf33e64eae7996b65846c7cb5e0a46e0a882ef179fd89654afa as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.20@sha256:0a4eaa0eecf5f8c050e5bba433f58c052be7587ee8af3e8b3910ef9ab5fbe9f5

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-gitea-release"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-gitea-release"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-gitea-release"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-gitea-release"

COPY --from=build /src/dist/wp-gitea-release /bin/wp-gitea-release
ENTRYPOINT ["/bin/wp-gitea-release"]
